version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-exec-exp
    container_name: flask-exec-exp
    volumes:
      - ${PWD}:/app
    ports:
      - "8080:8080"
    restart: on-failure
    working_dir: /app
    command: [ "sleep", "infinity" ]
